# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f003cf7dcf74410d11bfbf3ad4c15c6a0d4bd6177f51cf5d4d8ed47aa41ef129a8fc208f4a4478ee5ebe4c4d8deffd9c4b514ecc5310b6e33d6f68f9123779f

test:
  secret_key_base: 98522dce8fe3dc6980a3e37fa41ba17c1f70ddab9426460d64db62c8b8b2b4b5b61b279c78dc321b84259d56941fd94028cce0cfa3f005a059d740696126f40e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
